
mybatis:
  typeAliasesPackage: com.demo.entity
  mapperLocations: classpath:/mapper/*.xml

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_blog?useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
server:
  port: 8089
